inherit_gem:
  rubocop-infinum: rubocop.yml

require:
  - rubocop-infinum
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'exe/polariscope'

Rails:
  Enabled: false
